<?php
$text = "<h2>" . __( 'Important Notes', 'Igefilter' ) . "</h2>";
$text .= "<ol>";
$text .= "<li>" . __('Igefilter includes default options settings that will apply automatically.', 'igefilter') . "</li>";
$text .= "<li>" . __('If you mess up one of the following inputs, then clear the field (make it blank), hit "update options," and then the default values will reappear. Then, you <b>must hit "update options" again</b> in order to save the new value.', 'igefilter') . "</li>";
$text .= "</ol>";
$text .= "<h2>" . __( 'General Options', 'igefilter' ) . "</h2>";
$text .= "<h3>" . __( 'Default Bible Translation', 'igefilter' ) . "</h3>";
$text .= "<p>" . sprintf( __( 'The igefilter supports any version from the <a href="%s" title="Online Biblia">Online Biblia</a>', 'igefilter' ), 'http://www.online-biblia.ro/' ) . "</p>";
$text .= "<h3>" . __( 'Igefilter Mode', 'igefilter' ) . "</h3>";
$text .= "<p>" . __('You can use this plugin two ways; it can either filter your posts every time someone views them (dynamic), or it can permanently filter the posts whenever you create or edit them (static). If (1) you have a medium to high traffic site and (2) you use lots of verse references in your posts, then you probably want to use static mode. Otherwise, most low traffic blog sites should be OK in dynamic mode.', 'igefilter') . "</p>";
$text .= "<h4>" . __('Considerations for Static Mode', 'igefilter') . "</h4>";
$text .= "<ol>";
$text .= "<li>" . __('If Online Biblia changes their interface, then your old posts won\'t work right even if you update this plugin (whereas if you use dynamic substitution updating the plugin fixes all old and future posts transparently). This is not a theoretical consideration--the Bible sites have changed their interfaces since this plugin was first developed and they are likely to do so again.', 'igefilter') . "</li>";
$text .= "<li>" . __('If you change your default Bible translation then old posts will not be updated to reflect your new preference. Since it only changes posts when you edit them, you need to go back through all your old posts with Bible references and edit them to cause the plugin to take effect', 'igefilter') . "</li>";
$text .= "</ol>";
$text .= "<h3>" . __( 'Link CSS Class', 'igefilter' ) . "</h3>";
$text .= "<p>" . __('CSS class to apply to filtered links, for use in optional link styling. Valid class names must begin with a letter or number, and contain only letters, numbers, underscores, and hyphens.', 'igefilter') . "</p>";
$text .= "<h3>" . __( 'Open Link in New Tab/Window', 'igefilter' ) . "</h3>";
$text .= "<p>" . __('If set to true, adds target="_blank" to scripturized links, causing the links to open in a new window or tab.', 'igefilter') . "</p>";
$text .= "<h2>" . __( 'Credits: "Give honor to whom honor is due"', 'igefilter' ) . "</h2>";
$text .= "<h3>" . __( 'Original scripturizer Perl MovableType Module from which igefilter is derived:', 'igefilter' ) . "</h3>";
$text .= "<ul>";
$text .= "<li>" . sprintf( __( '<a href="%s">Dean Peters</a>', 'igefilter' ), 'http://www.HealYourChurchWebSite.com/') . "</li>";
$text .= "</ul>";
$text .= "<h3>" . __( 'Additional Credits for Perl Movable Type Module:', 'igefilter' ) . "</h3>";
$text .= "<ul>";
$text .= "<li>" . sprintf( __( '<a href="%s">Jonathan Fox</a>', 'igefilter' ), 'http://vulpecula.us/~jon/' ) . "</li>";
$text .= "<li>" . sprintf( __( '<a href="%s">Jason Rust</a>', 'igefilter' ), 'http://rustyparts.com/blip/' ) . "</li>";
$text .= "<li>" . sprintf( __( '<a href="%s">Joseph Markey</a>', 'igefilter' ), 'http://thegreatlands.com/archives/000032.html' ) . "</li>";
$text .= "<li>" . sprintf( __( '<a href="%s">Brian A. Thomas</a>', 'igefilter' ), 'http://www.brianathomas.com/archives/2005/01/17/editing-igefilter/' ) . "</li>";
$text .= "<li>" . sprintf( __( '<a href="%s">Rob Hulson</a>', 'igefilter' ), 'http://www.robhulson.com/archives/000073.html' ) . "</li>";
$text .= "</ul>";
$text .= "<h3>" . __( 'Port to PHP WordPress Plugin:', 'igefilter' ) . "</h3>";
$text .= "<ul>";
$text .= "<li>" . sprintf( __( '<a href="%s">Glen Davis</a>', 'igefilter' ), 'http://www.glenandpaula.com/' ) . "</li>";
$text .= "<li>" . sprintf( __( '<a href="%s">Laurence O\'Donnell</a>', 'igefilter' ), 'http://laurenceo.com/' ) . "</li>";
$text .= "</ul>";
$text .= "<h3>" . __( 'WordPress Plugin Documentation and Development', 'igefilter' ) . "</h3>";
$text .= "<ul>";
$text .= "<li>" . sprintf( __( '<a href="%s">Chip Bennett</a>', 'igefilter' ), 'http://www.chipbennett.net/' ) . "</li>";
$text .= "</ul>";
?>